"""Add new fields to StudentRecord

Revision ID: 36f9fbfee6d8
Revises: 
Create Date: 2025-03-13 11:26:07.195210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f9fbfee6d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_section', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mother_tongue', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('ethnic_group', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address_house_no', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address_barangay', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address_province', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('learning_modality', sa.String(length=50), nullable=False))
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('type_of_offense',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.alter_column('type_of_offense',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('learning_modality')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('father_name')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('address_province')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_barangay')
        batch_op.drop_column('address_house_no')
        batch_op.drop_column('religion')
        batch_op.drop_column('ethnic_group')
        batch_op.drop_column('mother_tongue')
        batch_op.drop_column('age')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('grade_section')

    # ### end Alembic commands ###
