"""Remove learning_modality field from StudentRecord

Revision ID: cd221ce75b74
Revises: bbdca89ef13b
Create Date: 2025-03-13 14:07:20.586236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd221ce75b74'
down_revision = 'bbdca89ef13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.drop_column('learning_modality')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_modality', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
