"""Initial migration

Revision ID: 272993ea3eac
Revises: 
Create Date: 2025-05-01 12:01:59.128237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272993ea3eac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lrn', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('mother_tongue', sa.String(length=50), nullable=True),
    sa.Column('religion', sa.String(length=50), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('municipality_city', sa.String(length=100), nullable=True),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('contact_number', sa.String(length=15), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lrn')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('offense_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offense_type', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('additional_info', sa.String(length=500), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offense_records')
    op.drop_table('users')
    op.drop_table('student_information')
    # ### end Alembic commands ###
