"""Add cascade delete to offenses

Revision ID: b3897fa14a57
Revises: a5bebe111341
Create Date: 2025-05-02 11:12:10.891382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3897fa14a57'
down_revision = 'a5bebe111341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offense_records', schema=None) as batch_op:
        batch_op.drop_constraint('offense_records_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student_information', ['student_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offense_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('offense_records_student_id_fkey', 'student_information', ['student_id'], ['id'])

    # ### end Alembic commands ###
