"""Fix ForeignKey in OffenseRecord

Revision ID: d028bd9fe240
Revises: b3897fa14a57
Create Date: 2025-05-08 13:33:03.141705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd028bd9fe240'
down_revision = 'b3897fa14a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offense_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offense_type', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('offense_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offense_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offense_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('additional_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_information.id'], name='offense_records_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='offense_records_pkey')
    )
    op.drop_table('offense_record')
    # ### end Alembic commands ###
